server:
  port: 18000

spring:
  application:
      name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
            - Path=/api/v1/auth/**

        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/v1/stores/**
            - Path=/api/v1/categories/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
        # Swagger ??? ???
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/api-docs/**
          filters:
            - RewritePath=/user-service/api-docs, /api-docs
        - id: store-service-api-docs
          uri: lb://store-service
          predicates:
            - Path=/store-service/api-docs/**
          filters:
            - RewritePath=/store-service/api-docs, /api-docs
        - id: reservation-service-api-docs
          uri: lb://reservation-service
          predicates:
            - Path=/reservation-service/api-docs/**
          filters:
            - RewritePath=/reservation-service/api-docs, /api-docs
        - id: review-service-api-docs
          uri: lb://review-service
          predicates:
            - Path=/review-service/api-docs/**
          filters:
            - RewritePath=/review-service/api-docs, /api-docs
        - id: notification-service-api-docs
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/api-docs/**
          filters:
            - RewritePath=/notification-service/api-docs, /api-docs
        - id: ai-service-api-docs
          uri: lb://ai-service
          predicates:
            - Path=/ai-service/api-docs/**
          filters:
            - RewritePath=/ai-service/api-docs, /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /user-service/api-docs
      - name: store-service
        url: /store-service/api-docs
      - name: reservation-service
        url: /reservation-service/api-docs
      - name: review-service
        url: /review-service/api-docs
      - name: notification-service
        url: /notification-service/api-docs
      - name: ai-service
        url: /ai-service/api-docs