name: gateway CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git repository checkout
        uses: actions/checkout@v4

      - name: permission for gradlew 권한 부여
        run: chmod +x gradlew

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          docker build -t gateway:latest .
          docker tag gateway:latest ${{ secrets.ECR_URI }}:latest
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 \
            | docker login --username AWS --password-stdin \
              147847019395.dkr.ecr.ap-northeast-2.amazonaws.com
            
            docker pull ${{ secrets.ECR_URI }}:latest
            docker stop gateway || true
            docker rm gateway || true
            docker run -d \
              --name gateway \
              --env-file /home/ec2-user/gateway.env \
              -p 18000:18000 \
              ${{ secrets.ECR_URI }}:latest
